FROM ubuntu:20.04

ARG ANSIBLE_VERSION="4.8.0"
ARG PLAYBOOK_FILE="golang.yml"
ARG PLUGIN_EXEC="go version"

RUN apt-get update -qq && \
    apt-get install -qq sudo python python3-apt python3-pycurl python3-pip python3-dev libffi-dev libssl-dev procps && \
    pip3 install -U setuptools && \
    pip3 install -q ansible==$ANSIBLE_VERSION && \
    ansible --version

WORKDIR /tmp/ansible-role-asdf
COPY  .  /tmp/ansible-role-asdf

RUN useradd -m deploy
RUN echo localhost > inventory

RUN ansible-playbook -i inventory -c local tests/$PLAYBOOK_FILE

RUN sudo -iu deploy bash -lc "asdf --version"
RUN sudo -iu deploy bash -lc "$PLUGIN_EXEC"
