FROM centos:7

ARG ANSIBLE_VERSION="2.7.4"
ARG PLAYBOOK_FILE="playbook.yml"

RUN yum -y install epel-release && \
    yum -y install sudo python python-devel python-pip gcc make initscripts libffi-devel openssl-devel && \
    pip install -q cffi && \
    pip install -q ansible==$ANSIBLE_VERSION && \
    ansible --version

WORKDIR /tmp/ansible-role-asdf
COPY  .  /tmp/ansible-role-asdf

RUN useradd -m vagrant
RUN echo localhost > inventory

RUN ansible-playbook -i inventory -c local tests/$PLAYBOOK_FILE

RUN sudo -iu vagrant bash -lc 'asdf --version'
